# Generated by Django 5.2.7 on 2025-11-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_estudiante_periodo_alter_estudiante_apoderado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
