# Generated by Django 5.2.7 on 2025-11-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_alter_estudiante_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='estado_matricula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
